// medium-feed.js

const localMediumFeedUrl = './data/medium-posts.json';

const postsContainer = document.getElementById('medium-posts-container');
const mediumFeedLastUpdated = document.getElementById('medium-feed-last-updated');
const numberOfPostsToShow = 3; // How many recent posts you want to display

function updateLastUpdatedText(fetchedAt) {
    if (!mediumFeedLastUpdated) {
        return;
    }

    if (!fetchedAt) {
        mediumFeedLastUpdated.textContent = 'Last updated: Unavailable';
        return;
    }

    const parsedDate = new Date(fetchedAt);
    if (Number.isNaN(parsedDate.getTime())) {
        mediumFeedLastUpdated.textContent = 'Last updated: Unavailable';
        return;
    }

    const dateParts = new Intl.DateTimeFormat('en-US', {
        timeZone: 'Asia/Kolkata',
        month: 'long',
        day: 'numeric',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        hour12: true
    }).formatToParts(parsedDate);

    const getPart = (type) => dateParts.find((part) => part.type === type)?.value;
    const month = getPart('month');
    const day = getPart('day');
    const year = getPart('year');
    const hour = getPart('hour');
    const minute = getPart('minute');
    const dayPeriod = getPart('dayPeriod');

    if (!month || !day || !year || !hour || !minute || !dayPeriod) {
        mediumFeedLastUpdated.textContent = 'Last updated: Unavailable';
        return;
    }

    mediumFeedLastUpdated.textContent = `Last updated: ${month} ${day}, ${year}, ${hour}:${minute} ${dayPeriod.toUpperCase()} IST`;
}

async function fetchAndDisplayMediumPosts() {
    if (!postsContainer) {
        console.error("Medium posts container not found!");
        return;
    }

    postsContainer.innerHTML = 'Loading Medium posts...'; // Show loading message

    try {
        // Fetch data generated by the GitHub Actions workflow
        const response = await fetch(localMediumFeedUrl, { cache: 'no-cache' });

        if (!response.ok) {
            // Handle HTTP errors from the generated JSON file
            throw new Error(`HTTP error! status: ${response.status}`);
        }

        // Parse the JSON response
        const data = await response.json();
        updateLastUpdatedText(data.fetchedAt);

        // Check if the generated feed has items
        if (data.status !== 'ok' || !data.items || data.items.length === 0) {
            postsContainer.innerHTML = '<p>Could not load Medium posts or no posts found.</p>';
            console.error('Error in local medium feed JSON or no items:', data);
            return;
        }

        // Clear the loading message
        postsContainer.innerHTML = '';

        // Loop through the JSON items and create HTML for each post
        // rss2json provides properties like 'title', 'link', 'pubDate', 'description'
        for (let i = 0; i < Math.min(data.items.length, numberOfPostsToShow); i++) {
            const item = data.items[i];

            // Extract data from the JSON item
            const title = item.title || 'No title'; // Use || '' for fallback
            const link = item.link || '#';
            // rss2json often provides ISO 8601 date, Date constructor handles it
            const pubDate = item.pubDate ? new Date(item.pubDate).toLocaleDateString() : 'No date';
            // Note: item.description often contains HTML. You might need sanitation
            // or extract plain text carefully if you display it. We'll stick to title/date/link for simplicity.

            // Create HTML elements for the post
            const postElement = document.createElement('div');
            postElement.classList.add('medium-post-item'); // Add class for styling

            postElement.innerHTML = `
                <h3><a href="${link}" target="_blank" rel="noopener noreferrer">${title}</a></h3>
                <p>${pubDate}</p>
                 <div class="post-link">
                     <a href="${link}" target="_blank" rel="noopener noreferrer">Read Post</a>
                </div>
            `;

            // Append the created post element to the container
            postsContainer.appendChild(postElement);
        }

    } catch (error) {
        console.error("Error fetching or processing Medium posts:", error);
        updateLastUpdatedText(null);
        postsContainer.innerHTML = '<p>Failed to load Medium posts.</p>'; // Show error message
    }
}

// Call the function to fetch and display posts when the script loads
fetchAndDisplayMediumPosts();
